package analizador.analizadorlexico.frontend;

import analizador.analizadorlexico.backend.ManejadorAreaTexto;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JEditorPane;

/**
 *
 * @author fabricio
 */
public class AreaTexto extends javax.swing.JPanel implements KeyListener, MouseListener {

    public String textoIngresado = "";
    private ManejadorAreaTexto mat = null;

    /**
     * Creates new form AreaTexto
     */
    public AreaTexto() {
        initComponents();
        jEditorPaneTexto.addKeyListener(this);
        jEditorPaneTexto.addMouseListener(this);
        mat = new ManejadorAreaTexto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneTexto = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelColummna = new javax.swing.JLabel();
        jLabelLinea = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(844, 455));

        jEditorPaneTexto.setBackground(new java.awt.Color(2, 36, 61));
        jEditorPaneTexto.setContentType("text/html"); // NOI18N
        jEditorPaneTexto.setFont(new java.awt.Font("Caviar Dreams", 0, 12)); // NOI18N
        jEditorPaneTexto.setForeground(new java.awt.Color(254, 254, 254));
        jEditorPaneTexto.setText("<html>\n<head>\n</head>\n<body style=\"color:white;font-family:Open Sans Light;padding:4px;\">\n<pre>\n</pre>\n</body>\n</html>\n");
        jEditorPaneTexto.setToolTipText("");
        jEditorPaneTexto.setCaretColor(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(jEditorPaneTexto);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 36, 61));
        jLabel1.setText("Linea:");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 36, 61));
        jLabel2.setText("Columna:");

        jLabelColummna.setForeground(new java.awt.Color(2, 36, 61));
        jLabelColummna.setText(" ");

        jLabelLinea.setForeground(new java.awt.Color(2, 36, 61));
        jLabelLinea.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelColummna, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 634, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabelColummna)
                    .addComponent(jLabelLinea))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JEditorPane getjEditorPane1() {
        return jEditorPaneTexto;
    }

    public void setjEditorPane1(JEditorPane jEditorPane1) {
        this.jEditorPaneTexto = jEditorPane1;
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        jLabelColummna.setText(Integer.toString(mat.getColumn()));
        jLabelLinea.setText(Integer.toString(mat.getLine()));
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        jLabelColummna.setText(Integer.toString(mat.getColumn()));
        jLabelLinea.setText(Integer.toString(mat.getLine()));
    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPaneTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelColummna;
    private javax.swing.JLabel jLabelLinea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
